<?php return array(
		'class'          => 'CUrlManager',
		'urlFormat'      => 'path',
		'rules'          => array(
				'local-events'                             => 'LocalEvent/Index',
				'local-event/<id:\w+>/*'                   => 'LocalEvent/view',
				'localevent-gallery/<id:\w+>/*'            => 'LocalEvent/gallery',
				'park/<id:\d\w+>/*'                        => 'park/view',
				'park-gallery/<id:\w+>/*'                  => 'park/gallery',
				'parks/*'                                  => 'park/Index',
				'register/*'                               => 'client/register',
				'valuations'                               => 'site/page/view/valuations',
				'help-van'                                 => 'site/page/view/help-van',
				'contact/*'                                => 'site/page/view/contact',
				'sales/*'                                  => 'property',
				'sendToFriend/<id:\d+>'                    => 'property/sendToFriend',
				'details/<id:\d+>'                         => 'property/view',
				'property-gallery/<id:\d+>/*'              => 'property/gallery',
				'topTwenty'                                => 'property/topProperties',
				//		'property/category/<id:\w+>/*'             => 'property/propertyCategory/',
				'links'                                    => 'Link/Index',
				'mailshot/<a:\w+>'                         => 'Mailshot/<a>',
				'<controller:\w+>/<id:\d+>/*'              => '<controller>/view',
				'<c:\w+>/<a:\w+>'                          => '<c>/<a>',
				'<controller:\w+>'                         => '<controller>/index',
				'<controller:\w+>/<action:\w+>/<id:\d+>/*' => '<controller>/<action>',

		),
		'showScriptName' => false,
);