<?php
session_start();
require("global.php"); 
require("secure.php"); 

if (!$_GET["action"]) {


$prop_id = $_GET["propID"];

if (!$_GET["sender"]) {
	$sender = "mark@interagent.co.uk";
	} else {
	$sender = $_GET["sender"];
	}


$sql = "SELECT * FROM property, area, branch, proptype, leasefree WHERE property.prop_ID = $prop_id  AND property.area_ID = area.area_ID AND property.Branch = branch.Branch_ID AND property.type_id = proptype.type_ID AND property.lease_free = leasefree.id_LeaseFree LIMIT 1";		
$q = $db->query($sql);
if (DB::isError($q)) {  die("property select error: ".$q->getMessage()); }

while ($row = $q->fetchRow()) {
	$pc = explode(" ",$row["Postcode"]);
	$strap = $row["description"];
	$addr = $row["Address1"].", ".$row["area_title"]." ".$pc[0];
	$area = $row["area_title"];
	$price = $row["Price"];
	$beds = $row["bedrooms"];
	$salelet = $row["SaleLet"];
	$type_id = $row["type_id"];
	$tenure = $row["leaseFree_Name"];
	$branch = $row["Branch_Title"];
	$tel = $row["Branch_Tel"];
	$fax = $row["Branch_Fax"];
	}

if ($type_id == 1 || $type_id == 2 || $type_id == 5 || $type_id == 7) {
	$proptype = "House";
	} elseif ($type_id == 3 || $type_id == 4 || $type_id == 6) {
	$proptype = "Apartment";
	} elseif ($type_id == 8) {
	$proptype = "Commercial";
	} elseif ($type_id == 9) {
	$proptype = "Live/Work";
	}

if ($salelet == 1) {
	$formatted_price = price_format($price)." ".$tenure;
	} elseif ($salelet == 2) {
	$formatted_price = price_format($price)."pw / ".price_format(pw2pcm($price))."pcm";	
	}	
	
$sql = "SELECT * FROM clients WHERE ";

if ($area) { 
	//$sql .= " clients.Areas LIKE '%".$area."%' AND ";
	}
if ($proptype <> "Any") {
	$sql .= " (clients.PropertyType = '".$proptype."' OR clients.PropertyType = 'Any') AND ";
	}
if ($price) {
	$sql .= " clients.MinPrice <= ".$price." AND clients.MaxPrice >=".$price." AND ";
	}
if ($beds) {
	//$sql .= " clients.Bedrooms >= ".$beds." AND ";
	}

if ($salelet == 1) {
	$sql .= " clients.Status = 'L'";
	} elseif ($salelet == 2) {
	$sql .= " clients.StatusLet = 'L'";
	}
echo "<!--".$sql."-->";
$q = $db->query($sql);
if (DB::isError($q)) {  die("client select error: ".$q->getMessage()); }

while ($row = $q->fetchRow()) {
	//$render .= $row["Email"]."\n";
	$emailCount++;
	}

$render = "          
kevcostello10@hotmail.com
anthony.spratt@justis.com
ellie@defected.com
drmishopk@yahoo.co.in
phoebe_jenkins@hotmail.com
paulo_greenwood@hotmail.com
lucinda3p@yahoo.com
yvonne.ndege@bbc.co.uk
pa216mb@gold.ac.uk
kaiser.s@zdf.de
mark.pailing@orange.net
kyrawilliams02@yahoo.co.uk
jemima_p@hotmail.com
andrea.koch@btinternet.com
andrea.koch@btinternet.co.uk
pbfbird@hotmail.com
ollie.squire@mvm.co.uk
rachel.amis@jimmychoo.com
d.watkins@elsevir.com
adrian.ellis@odpm.gsi.gov.uk
caroline.page@bbf.co.uk
andrew.calvert@frost.com
si_kelly@yahoo.com
katealdous27@hotmail.com
info@taniapsathas.com
e.collier@gold.ac.uk
adrian.ellis@paconsulting.com
pooting@hotmail.com
daniella_lee_wood@yahoo.co.uk
reneesharpe@yahoo.com
warlaura@hotmail.com
kenchow86@hotmail.com
jakinteriors@btinternet.com
bruce.mellor@macquarie.com
cjppage@hotmail.com
karen.clarke@cms-cmck.com
philipboucher@hotmail.com
helen@jaa.ndirect.co.uk
tim.edwards@emap.com
milesygoodman@yahoo.co.uk
barbaraoakey@hotmail.com
julius@breeze3.wanadoo.co.uk
sally.mackenzie@corpoflondon.gov.uk
g.smith312@btinternet.com
james.bailey@sainsburys.co.uk
s_allan90@hotmail.com
luby06@aol.com
anitabrissett@yahoo.co.uk
peter_rundell@yahoo.co.uk
delia.hyde@raincommunications.co.uk
evalondon@hotmail.com
tony.duckworth@chetwood-associates.com
poonam_33@hotmail.com
caroline_thorley@yahoo.co.uk
fmoorcroft@macmillan.org.uk
caroline.gammage@saatchi.co.uk
njausten@hotmail.com
heminapatel@hotmail.com
suzknig@aol.com
deborah.johnston@westlb.co.uk
JSanter@ahmm.co.uk
akaniceone@hotmail.com
rusticduke@hotmail.com
lara.davey@uk.pwc.com
rhancock@uk.ey.com
nicolablacker@yahoo.com
lukeanderton@hotmail.com
lauratmoo@yahoo.co.uk
cthorold@rediffmail.com
nicolajrobertson@hotmail.com
tim_g_webb@yahoo.co.uk
tam_walsh@yahoo.com
nicola.douglas@tbwa-london.com
kirsty_mcneice@yahoo.co.uk
v.nolda@btinternet.com
cassie@palmpictures.co.uk
assy4real@hotmail.com
mca_@btconnect.com
kofoare@btinternet.com
djstammers@yahoo.co.uk
sharrongibson@hotmail.co.uk
rabiatariq82@hotmail.com
gareth@webfire.co.uk
chris@chriskoning.com
ceeaton@btopenworld.com
rowena.pagdin@sagepub.co.uk
temy76@yahoo.com
sandra.sharpe2@btinternet.com
ag.webber@virgin.net
lawrence@peopleoflondon.com
rps195@hotmail.com
csouthgate@hotmail.com
john.wood@lloydstsb.co.uk
j_smith@zen.co.uk
catherine.deguillaume@ubs.com
bequinha21@hotmail.com
sonia.bhandari@mouchelparkman.com
cathy500@hotmail.com
louise.cakebread@hedra.com
luciecooper@hotmail.com
lucilla.r@virgin.net
mylesstinton@btinternet.com
suree.c@gmail.com
sphipps@ideo.com
r.shardlow@btinternet.com
bamba.dancer@virgin.net
s-baron@rocketmail.com
mark_lowman@hotmail.com
webegas@yahoo.co.uk
parkjj@aol.com
htw@dng.com
rachael_stevens@yahoo.com
ashleighogier@aol.com
joannelsimmons@yahoo.co.uk
katehayler1@aol.com
fedy_fort@yahoo.co.uk
steven.allmond@faraday.com
property@networksvg.com
jamieyurt@hotmail.com
kellynz05@yahoo.co.uk
reddmiller@hotmail.com
jamessbeattie@btopenworld.com
susanmulholland98@hotmail.com
alan@killip.co.uk
craigalansmith@hotmail.com
luce555@hotmail.com
andrew.dawe@beaufort-group.com
BEVERLEY.WEDDERBURN@REUTERS.COM
lindsay.gilchrist@tesco.net
hypearce@yahoo.co.uk
daisyr@vccp.com
anaylor@pfd.co.uk
caroline290374@hotmail.com
karolien.dehertogh@flybmi.com
gla_uk@hotmail.com
ruthpoone@hotmail.com
abaylis@mac.com
molegas@molegas.com
banaz@surf.co.nz
kellielashbrook@hotmail.com
lou.rol@btinternet.com
keri_powell@hotmail.com
lguarnera@msn.com
leon.hill@fishermeredith.co.uk
steve@owbridge.com
yasia.williams@mitchell-beazley.co.uk
ian.bradler@tube.tfl.gov.uk
jennie.sallows@tns-global.com
rose.kamara@virgin.net
lmrenals@hotmail.com
bolgersharon@hotmail.com
christopher.gil@btinternet.com
mattwingate77@hotmail.com
samantha@glidetechnologies.com
linda@jones8544.fsnet.co.uk
glassford100@aol.com
looran@hotmail.com
karen.king@tube.tfl.gov.uk
dpearson@uk.ibm.com
i@alfabeta.freeserve.co.uk
narafa@london.edu
paul.kilner@defra.gsi.gov.uk
saj_hussain7867@yahoo.co.uk
shutya@hotmail.com
supersar20@hotmail.com
house@downday.com
hugh.man@db.com
NICOLALATCH@HOTMAIL.COM
lco@uku.co.uk
clem@ipsgroup.co.uk
sam.luton@1webmail.net
j_pullicion@yahoo.com
jim.wheable@bbc.co.uk
pinkvamp1@hotmail.com
fhorlick@btinternet.com
ladydazl@hotmail.com
sophia_marques@hotmail.com
c.taylor@vam.ac.uk
issyfowler@yahoo.co.uk
peter.louw@hackney.gov.uk
jamie.trendall@bbc.co.uk
elizabeth@luminesce.freeserve.co.uk
seveo7@hotmail.com
rencallisto@hotmail.com
sarah_eldon@hotmail.com
rsewalker@02.co.uk
erin@presswatch.com
lloyd.burgher@lineone.net
dthomas2@westminster.gov.uk
medic_offshore@hotmail.com
tonywoollard@hotmail.com
ellie.wilcox@bbc.co.uk
burdenremoved@aol.com
tina.gardner@enviroment-agency.gov.uk
earthachaloner@aol.com
adoranthayes@yahoo.co.uk
patricia@smartaudiences.co.uk
J4rul@aol.com
panczako@op.pl
webby690@hotmail.com
kim@festival67.fsnet.co.uk
chrisfox74@hotmail.com
v.lawrence@iop.kcl.ac.uk
rachael.bolton@hyattintl.com
carolinefcodrington@hotmail.com
gokcenerdem@hotmail.com
ben.hull@newham.gov.uk
richardsonbenp@aol.com
keva267@aol.com
dom@ukonline.co.uk
matthewjames1971@btinternet.com
pva@dircon.co.uk
info@urbanangelsagency.com
cinde_lee@hotmail.com
Barbara.Lawrence@courtservice.gsi.gov.uk
eveireton8@hotmail.com
gregorysrush@yahoo.co.uk
vega@murden.me.uk
jangel247@hotmail.com
jojodavies@hotmail.com
maxenti@hotmail.com
ncloutter@london.oilfield.slb.com
louise_bull79@hotmail.com
thoward@btinternet.com
nyates1@hotmail.com
ssmith@featherstoneleigh.co.uk
debbiekhunter@gmail.com
a_olusanya@hotmail.com
erla_ka@yahoo.co.uk
scott.stickland@aviation-images.com
bsinturel@aol.com
honeyoe@hotmail.com
amy.wyatt@rogerschapman.co.uk
ellarhearn@hotmail.com
jonathan.s.clarke@uk.pwc.com
justjomiller@hotmail.com
pam@pkshaw.freeserve.co.uk
hannah.beacon@commerzbankib.com
ads@sdrecruitment.com
sboxall@nelson-bakewell.com
maggienickyouell@aol.com
sharyntan@hotmail.com
tiina.bjork@akqa.com
dzajer@yahoo.co.uk
simon.j.strutt@accenture.com
tim.shearring@telegraph.co.uk
robmoore_1@hotmail.com
tgodsal@yahoo.com
richard.day@sanctuarygroup.com
philipwilmann@aol.com
jimgallaghergolf@tiscalinet.ch
jamie.humphrey@amcgroup.com
nellist24@aol.com
jksresearch@hotmail.com
jinto3@hotmail.com
rsenapala@hotmail.com
s.gallagher@rondanin.co.uk
sean.bidder@vinylfactory.co.uk
hirokobray@yahoo.co.uk
julia@woosterstock.co.uk
jo.paton@blackheathhalls.com
sally@monkon.fsnet.co.uk
dom.landino@tradition.co.uk
JoPaton@dandelions.co.uk
sheen_laura@hotmail.com
dspurr@royalparks.gsi.gov.uk
r.young@supportaplc.com
daniel.lungu@gmail.com
griffian@aol.com
henry.longbottom@nortonrose.com
n.jerome@macmillan.co.uk
stefano.palazzi@gstt.nhs.uk
saskia.wirth@itn.co.uk
ola@bondai.pl
sdeguillaume@lambeth.gov.uk
alexprebble@hotmail.com
alisonjhammond@aol.com
emilyrowland@yahoo.co.uk
roger_odili@hotmail.com
angiea@europe.yahoo-inc.com
baljit2010@hotmail.com
c000@hotmail.co.uk
royandrew6@hotmail.com
lanriek@aol.com
leila@essentialbox.co.uk
maria@creativepartnershipmarketing.co.uk
marcin@gulbicki.plus.com
mjexcelmax@yahoo.co.uk
ROONEYHANNAH@HOTMAIL.COM
giulia@mornati.freeserve.co.uk
bajekukor@talk21.com
sarah_besley@hotmail.com
brandon@ims.gi
robert.randell@hotmail.com
kamer_akkor@yahoo.com
helen.stear@homeoffice.gsi.gov.uk
helen.stear@homeofficde.gsi.gov.uk
ellenfox@ntlworld.com
mililindsay@yahoo.co.uk
pearl.whyte@fha.org.uk
sneville@lambeth.gov.uk
elinor@degreeart.com
sharon.broadhead@blplaw.com
abravo@crossways.ac.uk
w.hauxwell@martinwardanderson.com
mike@niveus.org
ekoroni@hotmail.com
chris@anewnoise.co.uk
corwhihe2003@yahoo.com
annaabottuk@yahoo.co.uk
p.watkins@independent.co.uk
gary_hassett@hotmail.com
yiannakis.a@ntlworld.com
nkyval@hotmail.com
melcapeling@hotmail.com
lunas17@aol.com
mallison@cantorindex.co.uk
chris@chrisbergdahl.wanadoo.co.uk
gingerwhinger69@hotmail.com
sjridgway@supanet.com
rod@tricycle.co.uk
meci_nattero@yahoo.co.uk
iya@talktalk.net
walshsin@yahoo.com
cdfoxylady@hotmail.com
lynnes26@hotmail.com
bondarenkotatiana@hotmail.com
mart_welton@yahoo.co.uk
mserioux@hotmail.com
audeboulanger@hotmail.com
jcc155@hotmail.com
lisa@osullivan6838.fsnet.co.uk
marina.luchmun@durrants.co.uk
giancarlo1979@msn.com
campbelli@parliament.uk
selina.pavan@gmail.com
helen@acknowledge.co.uk
nveenarani@aol.com
betina.adams@virgin.net
sara.jubb@newsint.co.uk
emily.hayes@bbc.co.uk
carl.meek@sjberwin.com
jcarr@claridges.co.uk
achell@aldermanexecutive.com
cabradler@deloitte.co.uk
tidynp@aol.com
marc@sequelworks.com
claretempest@talk21.com
lemeiab@yahoo.co.uk
miloccos@yahoo.it
klarawan@hotmail.com
raquelreis@yahoo.com
jessica.mayman@sixtyuk.co.uk
dlsaipan@hotmail.com
vikram.khanna@csfb.com
scottjodie@hotmail.com
nikkicoker@hotmail.com
emma.l.cooper@accenture.com
saxe.roisin@mtvne.com
hubson@hotmail.co.uk
killee@eircom.net
banjomac@doctors.org.uk
m.pollard4@ntlworld.com
niki@bestshopever.com
francis@lcity.co.uk
alastair.burks@woolworths.co.uk
lynnedummett@aol.com
atda32374@aol.com
sofianaz@hotmail.com
maddiepetty@hotmail.com
jasebeckeiller@hotmail.com
Fritzroy.Smith@mht.co.uk
tamsie.thomson@inst.riba.org
frances.green@cliffordchance.com
jotagyeman@aol.com
kylie_e_allen@hotmail.com
KATIAVELI@AOL.COM
peternewton151@hotmail.com
mike.shephard@btinternet.com
samantha.regan1@btinternet.com
dan.mcrae@framestore-cfc.com
dbearman@uk.ey.com
pj_nosworthy@hotmail.com
nicoline_irving@yahoo.co.uk
christiana543@hotmail.com
robin.farmer@dhl.com
richamoah@yahoo.com
vkinice@yahoo.co.uk
adamkass@hotmail.com
bsreddy_m@yahoo.com
indira.sarsoza@ntlworld.com
petercooperlondon@yahoo.com
buggicsbars@yahoo.co.uk
battersbyjoe@hotmail.com
INDIRA.SARSOZA@ntl.world.com
seed2020@hotmail.com
nigel.oxbrow@tfpl.com
burger7@btinternet.com
missmunday19@yahoo.co.uk
s.gorton@unison.co.uk
philip@seone.co.uk
hmohamed@bwlaw.co.uk
yoong_tan@hotmail.com
erica@fpictet.com
lbsjoinery@hotmail.com
john_mcclymont@hotmail.com
armstrongj@frenchconnection.com
littlepinkbug@hotmail.com
alex.stolz@ukfilmcouncil.org.uk
katie.merritt@hiscox.com
manting-tang@yahoo.com
lucy.malsbury@mapeley.com
efjaylinks@aol.com
g-max@t-online.de
tim.jackson@holmans.co.uk
rebeca.perez@nhs.net
prop@cityandregional.com
gladysmizg@aol.com
seelan-1@ntlworld.com
deniseandantonia@hotmail.com
juliette.young@ukgateway.net
ALWYNCHARLESP@YAHOO.CO.UK
markmoris111@hotmail.co.uk
alans14@hotmail.com
dp@edp.demon.co.uk
milan.panchmatia@virgin.net
acole@channel4.co.uk
Avitajarvis@aol.com
jane.common@dailystar.co.uk
sheila.bugler@ofcom.org.uk
steadykey@yahoo.co.uk
CATHYCARR4@aol.com
YETUNDEO@AOL.COM
silversnake70@hotmail.com
ibrodie@brit.croydon.sch.uk
martin.kerr@celerant.cc
lovono@yahoo.com
brendan@low-profile.com
vickygashe@hotmail.com
nikki_ha22@hotmail.com
rs2_chobra@yahoo.co.uk
hmmcdaniel@ntlworld.com
pmutabazi@aol.com
silinaelena@hotmail.com
van_elliott@hotmail.com
emilymc71@yahoo.com
sarah.berlini@otis.com
dale.thompson@virgin.net
cogbeat@btopenworld.com
david.b@bostockandpollitt.com
shiggison@ureach.com
coumbaf@communitychannel.org
kevin.sl@virgin.net
diannemflatt@hotmail.com
spoons.by@virgin.net
joanna.allen@rothschild.co.uk
scott_neilson@hotmail.com
sarah@evorecruit.co.uk
humara@abidi.wanadoo.co.uk
elaine.clarke@ucl.ac.uk
everton@evewright.com
iainjh@orange.net
helen.mcilveen@blueyonder.co.uk
iain.macdonald@rbs.co.uk
beryl@grigg7171.freeserve.co.uk
willigan@hotmail.com
yolanderoreilly@hotmail.com
horseshoeinn@wyenet.co.uk
paddy4@o2.ie
richard@ogle20.freeserve.co.uk
branavan.retnasingham@ntlworld.com
j.ball@comicrelief.org.uk
zoe.zammit@morganstanley.com
crispp@rpsplc.co.uk
tom.butler@idmedia.com
lmckechan@iwm.org.uk
darren@amandahowardassociates.co.uk
richgale999@msn.com
riloula@onetel.com
wswan1n@smithfieldgroup.com
hannah.verdier@emap.com
razeena.macanmarkar@lovells.com
phillip@mydramarama.com
liz.pearson@highburywv.com
ckelly1uk@yahoo.co.uk
He1enSargent@fco.gov.uk
gattdave@yahoo.co.uk
eli9633@gmail.com
bert.neil@virgin.net
alya_chaudhry@hotmail.com
petermorton@freeuk.com
peita.richards@uk.pkf.com
cs_sander@yahoo.de
aderoche@westminter.gov.uk
aphroditekorou@yahoo.co.uk
post@interagent.co.uk
l.niven@bbk.ac.uk
lisa.dawson@nasnet.co.uk
m.gunderson@chelsea.arts.ac.uk
paultrivett@hotmail.com
vivyanker@hotmail.com
johnsonkaren@hotmail.com
psnewellprice@hotmail.com
crichards_589@hotmail.com
riss63@hotmail.com
susiewheeldon@yahoo.co.uk
sherinedewlett@yahoo.co.uk
jojomitchelson@hotmail.com
roshevron@mac.com
ee9nv@hotmail.com
tony.wood@acorn.ltd.uk
chris.ohare@investecmail.com
ian.c.ogara@accenture.com
kenny.wan@unitedclearing.com
ilonaszalay@yahoo.co.uk
aragontu@yahoo.co.uk
kcummins16@aol.com
samantha.english@burberry.com
hilary@AOL.co.uk
shelley_walker7@hotmail.com
holly.barron@citigatedr.co.uk
samempestbrooks@hotmail.com
tr229@cam.ac.uk
katrinampollock@hotmail.com
peterfoy@hotmail.com
elaine@alaska.net
d.williams@erco.com
goinroundtheworld@hotmail.com
deepa_vakil@yahoo.com
mahine70@hotmail.com
luizamachado6893@aol.com
o.d.p@another.com
lisa@limadesign.co.uk
shantell_delicious@yahoo.co.uk
catmansuy@lineone.net
david.pickles@virgin.net
jon.carson@homeoffice.gsi.gov.uk
harry@zeal.co.uk
bridgeslondon@aol.com
alison.farrier@loweworldwide.com
angela.clarke@bbc.co.uk
tayo2k@hotmail.com
lucyryan22@hotmail.com
carl.eatson@saatchix.co.uk
siri.melchior@gmx.net
lisa.naussedat@lgim.co.uk
nickpagan@hotmail.com
andrew.wilcox@playboytv.co.uk
lukebateman@hotmail.com
stephanie.alqaq@btopenworld.com
kirsty@kirstybushell.com
frances.green@shearman.com
sdure@stikeman.com
zoe.harris@trimediauk.com
kirsty_lamb@hotmail.com
waters@scossa.com
stellavive2003@yahoo.co.uk
jane_dunford@yahoo.co.uk
andrewk@acorn-homes.co.uk
pr9@soas.ac.uk
stephendavy@ntlworld.com
patriciaoneill44@hotmail.com
onsite99@worldonline.co.uk
sarah.potter@bensherman.co.uk
james_levene@hotmail.com
duquemin@dircon.co.uk
mike.merritt-holmes@exow.co.uk
gary.lynch@burohappold.com
michael.melis@natmags.co.uk
damoaten@hotmail.com
catrinw@ica.org.uk
frederick_udoaka@hotmail.com
eds@ezrs.com
sadye1@hotmail.com
davidcampbell007@hotmsil.com
sebastiano.plutino@bancaintesa.co.uk
paolaeunice@hotmail.com
neil.rumming@virgin.net
nelson_adrian@hotmail.com
isla@pilot.co.uk
jilmet@hotmail.com
lem.blackwood@hotmail.com
glw93@dial.pipex.co.uk
lufeitoza@hotmail.com
stuartf@ukinvest.uk.com
will@indian.co.uk
nicola@narratives.co.uk
ask@haveandhold.co.uk
dominic.gleeson@btinternet.com
a.nicholson@twentyfirst.com
susanb00@hotmail.com
matt@uva.co.uk
mjkamali@aol.com
bassetts@accamail.com
g.brickwood@lse.ac.uk
earthafrederick@yahoo.co.uk
austen@smallfamilybusiness.com
markcooper1968@yahoo.co.uk
robn@profilegroup.co.uk
diveenh@hotmail.com
colin@interagent.co.uk
jenny@interagent.co.uk
thanh@interagent.co.uk
julia@interagent.co.uk
becky@interagent.co.uk
emma@interagent.co.uk
arabella@interagent.co.uk
carladiego@hotmail.com
sara.naessens@pinsents.com
david@davidcloake.freeserve.co.uk
kristyn.mitchell@bankrestaurants.com
maxine_wilkie@hotmail.com
m.judd2@btinternet.com
rakhee.verma@bankers.co.uk
peacock_234@hotmail.com
issydyson@hotmail.com
norma.gaunt@edgepicture.com
abcdenicola@aol.com
gordon.h@zen.co.uk
romeoperes@romeoperes.com
simon.l.brown@aib.ie
lizarimoro@yahoo.co.uk
ceaperry@hotmail.com
carlaeshaw@hotmail.com
cazcj1@hotmail.com
jon.scholefield@accenture.com
mimoore001@yahoo.co.uk
cdefreyne@cantorindex.co.uk
kate.critchley@uclh.org
lorrainechi_78@hotmail.com
paul@duncannet.co.uk
pam@bushtheatre.co.uk
escjmartin@yahoo.co.uk
mbermondsey@mac.com
paulblaker@tiscali.co.uk
Carvillc@smuc.ac.uk
paulroberts@aitchgroup.com
michaelnjotsa@hotmail.com
hannah.delaney@kingsch.nhs.uk
anju.chadda@bt.com
andyjnhiggins@hotmail.com
chalkee_white@yahoo.co.uk
stuartcotterell@hotmail.com
tktran28@yahoo.com
joao.saraiva@cam-group.com
claire.rosindale@fortisbank.com
owatson@wedlakebell.com
amylangfield@yahoo.co.uk
planetarypea@yahoo.co.uk
kate_royal@yahoo.co.uk
alice@baverstock.fsnet.co.uk
carol.wint@cml.org.uk
rebekah_caudwell@hotmail.com
vicgee@hotmail.com
rsdcem@aol.com
ijasiewicz@hotmail.com
jburton@cbiepc.com
paul.morton@dacg.net
eric.addo@newsint.co.uk
sharonmccole@hotmail.com
tvintin@bloomberg.net
kevin.gleed@steel-design.co.uk
nandiwallace@hotmail.com
lauren.george@ubs.com
bill-begg@btconnect.com
bella@emergingmarkets.co.uk
craig.spital@gs.com
Welsh_one90@hotmail.com
verjoe@ntlworld.com
alpeshabroad@hotmail.com
liz.seymour@uktv.co.uk
jeff_melba@yahoo.co.uk
info@hiproject.com
admin@insighttdc.co.uk
oviawe4@yahoo.com
vickiscott5@hotmail.com
p.kotwinski@ucl.ac.uk
emma.jenkins@anderselite.com
jacksonc@bhf.org.uk
nal-izzi@phd.co.uk
ldavison@channel4.co.uk
pbarrett@eastwind.org.uk
rebecca.joe@abbey.com
lillian.chen@electricwordplc.com
matt.ball@hotwirepr.com
hassansuk@yahoo.co.uk
nct8872@fsmail.net
angelarhiannon@hotmail.com
jody.ward@gta-travel.com
jenneyryley@hotmail.com
rupasinghe@aol.com
ggiadaa@hotmail.com
lorraine.gibbs@defra.gsi.gov.uk
alexharding@hotmail.com
emma.barnes@gartmore.com
ameliagliksten@yahoo.co.uk
awilliams@exedia.com
info@i-sa.com
balucci203@aol.com
michelle.gopsill@bbc.co.uk
mice3d@yahoo.com
rserroukh@hotmail.com
RG.GREEN@virgin.net
sarah@flowergirls.freeserve.co.uk
tmatthews@c-london.co.uk
n.latimore@ry.com
hilary@brainstorm-uk.co.uk
jack@tinker99.freeserve.co.uk
sam.hinde@shell.com
gabikent@hotmail.com
katherinebrooke999@hotmail.com
maddiea@ntlworld.com
racheltimperlake@hotmail.com
nboyle@struttandparker.com
hugh@fecund.co.uk
grantwait@hotmail.com
siobhan.endean@amicustheunion.org
benbrookes@yahoo.com
aydinjazzyorange@hotmail.com
naomistollard@yahoo.co.uk
jessicafielding@netscape.net
johnny@smcheng.freeserve.co.uk
kim@flare-design.co.uk
dom@aliveband.co.uk
nickwoodford@highstream.com
jkwooster@yahoo.co.uk
jola2110@aol.com
miranda@atabraham.fsnet.co.uk
avaice@ntlworld.com
Anthony_Hodgson@scee.net
mariaureta@hotmail.com
rsg@dentonwildesapte.com
Jurgita.gomez@bbc.co.uk
bethan@alexander-richards.com
kelly.sullivan@bbc.co.uk
diana.mayaveram@1webmail.net
gwr22@cam.ac.uk
property@scootersinc.co.uk
hai.tran@sieberthead.com
zoe.blakemore@freshfields.com
lindsayskilling@hotmail.com
bethan.bailey@ogilvy.com
S.Shannon-alumni@lse.ac.uk
fardeensidik@hotvoice.com
matthewtstevens@yahoo.com
vivvy56@hotmail.com
t_sabanathan@yahoo.co.uk
paul@preloaded.com
frellier@yahoo.co.uk
eliza@ktidbury.fsnet.co.uk
anthonylowe02@aol.com
j.fergusonsmith@ntlworld.com
polly.waite@harpercollins.co.uk
pztmurphy@hotmail.com
ramsy@telkomsa.net
jackburns4@hotmail.com
sheldonsarah@aol.com
anna.cumming@blplaw.com
julian.dailly@sainsburys.co.uk
james.lavin@cfsms.nhs.uk
kgross@no10.x.gsi.gov.uk
vhaines@bridgeport.edu
gladysacquah@btinternet.com
sean@encoretix.co.uk
emwayman@aol.com
mpopom@hotmail.com
justinewright@mostwanted.com
felix.fiennes@virgin.net
kirstybrownuk@hotmail.com
kevin.gould@strategicthought.com
sheeraz.ahmed@csfb.com
bs83qp@aol.com
sonia.b.hodge@talk21.com
anna.evans@craikjones.co.uk
heyjude@btopenworld.co
argy@milocreative.com
dafyddhumphreys@yahoo.co.uk
asope@hotmail.com
prina.patel@datadirectltd.co.uk
nick@flatmints.com
dm@kent.ac.uk
nick.roberts@masons.com
chloe.roberts@roughguides.com
jocridge@yahoo.co.uk
sandie.owens@newsint.co.uk
dennis.isp@blueyonder.co.uk
victoriabacon@hotmail.com
philip.gordos@btopenworld.com
sofie@Karlsson2494.freeserve.co.uk
isaactooby@hotmail.com
helenvj@excite.com
renapapa@hotmail.com
lorna.pepper@cbre.com
viccove@hotmail.com
charlieharrity@hotmail.com
arupm@yahoo.com
jaqueline.monro-higgs@five.co.uk
jtrebilcock@btinternet.com
cwalder@aol.com
featherstonesimon@hotmail.com
tim_143@hotmail.com
rachel.bridgman@wbr.co.uk
nell2000@freenetname.co.uk
kathy_duggan@btinternet.com
raj@bansals.com
kirstine@scanna-msc.com
steve.simons@ntlworld.com
carina@bluething.co.uk
rob_burns75@hotmail.com
sam@gorgeousgroup.com
tillyhardy@hotmail.com
lreiff@ufji.com
jclayton@westminster.gov.uk
anettefajardo@yahoo.co.uk
dtblack@hotmail.com
devine@edwards-drayton.freeserve.co.uk
samantha@terrapartnership.co.uk
info@mleaf.co.uk
Imtiaz.Kaderbhoy@sainsburys.co.uk
reneewalsh931@aol.com
e.dowson@transworld-publishers.co.uk
marcussiddons@hotmail.com
annaroberts@hotmail.com
monkfishmurray@hotmail.com
simon.atter@barclayscorporate.com
tamarahshakir@hotmail.com
alexandrahouse@yahoo.com
mbrown@hitentertainment.com
gemmahogarth@hotmail.com
alan.bingle@emap.com
manali_humble@yahoo.co.uk
soup.dragons@virgin.net
fiona.ingham@sweetandmaxwell.co.uk
mb0ss@india.com
cheriebyrne1@hotmail.com
biancalevy@hotmail.com
farzana.bharmal@mortgageuk.com
anneke@pad.dircon.co.uk
raggatings@hotmail.com
nisha.ladwa@fas.gov.uk
kerryduggan250@aol.com
fdevilliers@yahoo.com
alanandsue.papier@tesco.net
victyoria@hotmail.com
m.mizzi@ntlworld.com
ian@bdrecruitment.co.uk
asnesu.dvd@virgin.net
mclark@tcstown.com
sljbrown@hotmail.com
hassan460@hotmail.com
chris.mines@ba-londoneye.com
katrina.corcoran@hp.com
laurie.basannavar@publicis.co.uk
yasminpunjani@hotmail.com
mkdclewis@aol.com
louiserbsymons@yahoo.com.au
timhall714@hotmail.com
heidi_ed@yahoo.co.uk
alexhooper76@hotmail.com
gokmen_kerey@msn.com
claudias@foe.co.uk
femoseni@aol.co.uk
h.chang@morganstanley.com
b.hassan@solutions4living.com
cgouleme03@hotmail.com
elestewart@aol.com
annaward@cheerful.com
steven_mc_govern@hotmail.com
gmoorsimmonds@02.co.uk
s.coleshill@hemscott.net
mmalate@server1.jehyde.co.uk
simont@stconsulting.co.uk
shellyaustinpowers@hotmail.com
peter@q2designs.com
tony@capellatechnology.com
MELISSA.LEWIS@WWAVRC.CO.UK
kate@mmasskm.demon.co.uk
andyevs1@hotmail.com
adaadama@hotmail.com
robgate@btopenworld.com
biancabewley@aol.com
mail@fleurjago.co.uk
mermaidaskew@yahoo.com
barn.gaze@tiscali.co.uk
joanna.latham@dtz.com
maryeckley@hotmail.com
claire.cunningham@bbc.co.uk
san51342@hotmail.com
naghmir@hotmail.com
ausar1@hotmail.com
louisa.gray@pauffley.com
gemma@interagent.co.uk
vmuhlbauer@micropat.com
jurie.wickham@babtie.com
joanna.bushell@btinternet.com
kl_taylor@hotmail.com
patriciabennett@supanet.com
t-mccann@dfiid.gov.uk
shelley@bbpr.com
mccreeryd@hotmail.com
kevinjpayne@ntlworld.com
Mehmet.Osman@btinternet.com
ratherley@yahoo.com
omar@wbr.co.uk
rele_james@hotmail.com
lizeegan@aol.com
simonw@simonwilcox.co.uk
celalkuccuk@yahoo.co.uk
aebrahimuk@yahoo.co.uk
etaiga@hotmail.com
ben_phillips22@hotmail.com
george.pagliero@liontv.co.uk
mckennasworld@aol.com
agirlalien@hotmail.com
julian_mason@scee.net
croallynt@dulwich.org.uk
mkarania@hotmail.com
muzinha@netcomuk.co.uk
nishel.priya@natmags.co.uk
krazemags@aol.com
ajboulanger@hotmail.com
rsekhon81@hotmail.com
amie@amiewong.freeserve.co.uk
fjfiona@hotmail.com
smuckley@eno.org
conor.hutchinson@intellexis.com
allend@bhf.org.uk
katie-tabi@tiscali.co.uk
tdufficy@unitedclearing.com
b_laubi@hotmail.com
ciara.byrne@lehman.com
kellibayliss@hotmail.com
mandrews@christies.com
a_omosan@hotmail.com
copix@clara.co.uk
orchard.cottage@clara.co.uk
andrew.skinner@atisrealweatheralls.com
markpallis@yahoo.co.uk
daire.gilmore@jpmorgan.com
christian.thomas@aon.co.uk
heather.mitchell@synovate.com
celal_adict17@yahoo.com
zoe.oconnor@lstrillium.com
jamesholness@hotmail.com
jim.wheble@bbc.co.uk
sony.brown@fandc.com
ben.jones@dft.gsi.gov.uk
suzykeadell@hotmail.cpm
alisonwynn365@hotmail.com
guy@thecherwellgroup.com
lucy.coull@egs.com
glen.wild@equitas.co.uk
colinmcmaster10@hotmail.com
lydiabell1975@aol.com
meduffield18@hotmail.com
stevomitchell@hotmail.com
kathyannlewis@hotmail.com
susan@freedom-media.com
muaktr@hotmail.com
hanwilliams2@yahoo.com
deepajohal@hotmail.com
raymond@latham.freeserve.co.uk
malinirishi_21@yahoo.co.in
eurobrit1973@yahoo.co.uk
siv_kri@hotmail.com
chris@designuk.com
unionst@btopenworld.com
laura_morris@turntown.co.uk
bronwenloftus@hotmail.com
chris.miles@capita.co.uk
andrewa01@msn.com
klwu@ukgateway.net
matildebiacchi@hotmail.com
vamadin@aol.com
kristin_sherman@hotmail.com
carolanjoanna@hotmail.com
spbcphd@iop.kcl.ac.uk
elidore@hotmail.com
marie_magimay@hotmail.com
jadavis_137@yahoo.com
anthony.stephen.nolan@citigroup.com
amy@camron.co.uk
stepb3@aol.com
paul.lyes@gs.com
klogie@gmail.com
heidi.rowsell@clyde.co.uk
martinjj8@aol.com
powermax@hotmail.com
nikhil.dacosta@sgey.com
alastair.massey@uk.pwc.com
andersoc@visa.com
alex.shone@freud.com
kath_lambert@lineone.net
georgina.mincher@bds-beechwood.co.uk
caroline.pyke@corpoflondon.gove.uk
beth@wrc.org.uk
aaaempire@hotmail.com
tristan_connell@hotmail.com
cbedrane@hotmail.com
neil.rumming@vigrin.net
philiprudolf@lycos.com
teresathorn@msn.co.uk
tamsin.musson@princesstv.com
iraidamg@aol.com
mick.paterson@btopenworld.com
nicolawadden@onetel.com
maria.marsh@dewhirst.com
herratyc@foxkids.co.uk
pollylittle4@hotmail.com
clarkgregory45@hotmail.com
general@ronaldboddy.com
faye@goulanbros.co.uk
d_calvera@yahoo.co.uk
cedogorman@hotmail.com
tania.cot@hotmail.com
joanna.latham@dtrz.com
freddielad@hotmail.com
sophiehornby@hotmail.com
jsilver@channel4.co.uk
layla.dale@warnermusic.com
sally@jojomamanbebe.co.uk
stewhartley@hotmail.com
battlecake@hotmail.com
ecreasey@yahoo.com
csbennett@ekno.com
ben.ryan@donaldsons.co.uk
Eilin_OCarroll@ssga.com
angela.christie@aventis.com
famous_arash@yahoo.com
nataliejaynepoole@hotmail.com
cathy@thecogency.com
jason.rhodes@pjpubs.com
hunter_caroline@hotmail.com
simonandamy@hotmail.com
sacha_p@zenith-entertainment.co.uk
jhthody@hotmail.com
marysemignott@hotmail.com
susanneaderhold01@yahoo.co.uk
melanie.bloxham@bleaktochic.com
anabel@bravefilms.com
nik.windsor@bdf-beechwood.co.uk
aireswalterdossantos@yahoo.co.uk
jon.howes@london.sema.slb.com
helen.baird@bbc.co.uk
adaminglis@yahoo.co.uk
mandy.kirk@lewisham.gov.uk
clare@slproperties.co.uk
tamerbishay1@aol.com
srujanavijayan@hotmail.com
sophie.park@tarlolyons.com
sumayap@aol.com
rogerg@yahoo.co.uk
anjmraz@aol.com
jasperbell@dsl.pipex.com
lawal.owonifari@lonex-property.com
gem_s2002@hotmail.com
helen@artsdesire.co.uk
arne.s@virgin.net
robert_leigh_banks@yahoo.com
mitchell_suzanne@hotmail.com
phargadon@randomhouse.co.uk
lesleywong_2000@yahoo.com.au
monk21uk@yahoo.co.uk
bauchant@yahoo.com
yourottenegg@hotmail.com
citydreams@yahoo.com
bianca.ruakere@shell.com
debi6197@hotmail.com
plews_andrew@hotmail.com
rwilcock@bankofny.com
pas027@hotmail.com
nompilomabena@hotmail.com
bondgirluk@hotmail.com
pmbigpaul@hotmail.com
clairebrown22@hotmail.com
anne.robin@warnermusic.com
normangillard@hotmail.com
sandraclout@aol.com
kpond@imprintplc.com
graeme.fotheringham@uk.abnamro.com
mrtorrisi@aol.com
johnebennett@ic24.net
sorraya.baig@talk21.com
mikefisher75@hotmail.com
ejaz123@hotmail.com
justin.everitt@everittboles.com
daniel@peppermint.co.uk
laffeyjoanne@hotmail.com
dan.naylor@durrants.co.uk
reddyhoff9@hotmail.com
iankinsey@hotmail.com
kevinlilley@home298.fsnet.co.uk
rebecca_seter@hotmail.com
vgotsell@hotmail.com
ficall@lineone.net
ldaniels@doctors.org.uk
commanderemily@hotmail.com
eleanor_young@hotmail.com
garry@suola.co.uk
nwilliamson@keoghcaisley.com
brianharrison86@yahoo.co.uk
blackmelon4@hotmail.com
alisonmacrae2000@hotmail.com
michelle.cort@icr.ac.uk
kamran_soltan@hotmail.com
commandere@parliament.uk
despatch@sibylcolefax.com
stephen.gambrell@virgin.net
slphiegates@hotmail.com
alexandra.schoeb@lon.rep.admin.ch
anthony@rddavidson.co.uk
stella_elvergel@hotmail.com
adrienne_goss@hotmail.com
anwuzia@aol.com
cathperry75@yahoo.com
andrew@locomotion.co.uk
starwalk@globalnet.co.uk
dionne@impacttlimited.com
dsullivan@akllp.com
fran_h_horne@hotmail.com
joanna.yeldham@bbc.co.uk
sarah.oconnell@bbc.co.uk
felixmilns@totalise.co.uk
ehiomof@hotmail.com
katsgroove@hotmail.com
adz_r1988@hotmail.com
propertyportfolio@yahoo.co.uk
mark@stevenson.fsnet.co.uk
suzepetch@hotmail.com
jbullent@hup-mitpress.co.uk
rebecca_97@hotmail.com
nickygrillo1@hotmail.com
geekgirlrach@hotmail.com
jennifer_duncan@yahoo.com
etrevlyanjohnson@hotmail.com
anita.kamat@yahoo.com
llewellyncollymore@yahoo.co.uk
uberto1212@hotmail.com
davidcarmenman@yahoo.co.uk
me.electrics@virgin.net
sweetnalini@hotmail.com
jo.lomas@fco.gov.uk
quimdamestra@aol.co.uk
smolloy@actionaid.org.uk
craig_munro@westlb.co.uk
mariongraham6@hotmail.com
rebeccaholman@onetel.com
sarahcauston@yahoo.co.uk
magrobchung@postmaster.co.uk
markbaker_bsc@hotmail.com
bellme@mailcity.com
tanyasurendra@hotmail.com
ian_mcoulson@hotmail.com
becky.hunter@dk.com
jbeese@rfh.org.uk
rdpearce@hotmail.com
ersin4@hotmail.com
annette@brucedunlop.com
amo_2k2@hotmail.com
aabailey88@hotmail.com
annemahoney@tesco.net
jane.sweeting@dwp.gsi.gov.uk
belinda.champion@fsmail.net
fmkkw@renren.fsnet.co.uk
refielding@yahoo.com
cetamafairy@yahoo.co.uk
nonyen@hotmail.com
denaylor@yahoo.com
Jill@beesplease.co.uk
cathrine.ellis@mac.com
dagababian@channel4.co.uk
kate.hemmings@fco.gov.uk
quaywegirl@hotmail.com
chris_britto@hotmail.com
hog@orange.net
davevfisher@hotmail.com
eforsb@yahoo.com
musamoyo@hotmail.com
slickrick43@aol.com
benwest80@hotmail.com
helenshipley83@hotmail.com
sairahawan@mac.mail.com
n.swain1@ntlworld.com
planetjojo@yahoo.com
benjo1@onetel.com
tonywjewell@yahoo.co.uk
mike@sheppardrobson.com
m_davis1979@hotmail.com
gabrielle.procter@hackney.gov.uk
zoe.nauman@sundaymirror.co.uk
joearafa@writing.com
april.read@tesco.net
cristina.macias@ssmb.com
gwen.rule@btopenworld.com
djhatakia@aol.com
heq2000@yahoo.co.uk
ksjost@yahoo.com
michaelstaien@hotmail.com
abi.bankole@echarris.com
sherineM@ipr.org.uk
amsaul@hotmail.com
anna.puttick@collegehill.com
jerry_katelosty@hotmail.com
melissa_365@hotmail.com
l_ag2@hotmail.com
kevahoy@aol.com
emily.davidson@nng.co.uk
kawosemo@yahoo.co.uk
hburkitt@hotmail.com
mharan@globalnet.co.uk
karen.butcher@camden.gov.uk
tinaschuler@hotmail.com
avantiass1@aol.com
mark@vivid.co.uk
nsalter@hotmail.com
rehana_ali@hotmail.com
donna.flanagan@tikit.com
trc@eashaw.com
jim.spencer@ogilvy.com
chandynath@hotmail.com
fiona.oloo@dti.gsi.gov.uk
kechinz@yahoo.com
patrickkalungi@yahoo.co.uk
sally-anne.callick@jpmorgan.com
house@dubar.com
gfmoss@bigfoot.com
christian.rudolf@ubs.com
melanie.etches@sainsburys.co.uk
terry.gaymes@kcl.ac.uk
kaiting.chiang@barcap.com
luisa@cannakendall.co.uk
maryc25@aol.com
estebanlee2@hotmail.com
sitakmsr@hotmail.com
jennifer@stubbs5577.fsnet.co.uk
elisabethjebb@yahoo.co.uk
kannecy@hotmail.com
snotsid@yahoo.com
adetolab@aol.com
manish@ims-limited.net
n_porakishvili@hotmail.com
leemoran69@yahoo.co.uk
titi90@hotmail.com
fro_bo@hotmail.com
susannaeriksson2@aol.com
em.rumble@btinternet.com
natalie.masse@tiscali.co.uk
marcelaruiz10@yahoo.com
melanie.hascher@gs.com
jsilmon-clyde@maninvestments.com
sue.perera@btinternet.com
jpbenstead@freeuk.com
vickyfoxcroft@hotmail.com
sophtel@aol.com
jo.manderson@talk21.com
nic.teeman@towerhamlets.gov.uk
lotte1999@yahoo.com
truong_truong78@yahoo.com
wconnelly@bankofny.com
muddlekim@hotmail.com
j_saville@hotmail.com
drg1406@aol.com
louxuejing@yahoo.com
stephenakinjewe@hotmail.com
karolfik@yahoo.co.uk
charlotteodonovan@pro-rec-org.com
witts1@btopenworld.com
colin_a_yeo@hotmail.com
otteryboy@hotmail.com
barry.gilbraith@virgin.net
dawn.wiltshire@uk.ing.com
stefanieoakley@hotmail.com
bobiegee@hotmail.com
lucieannharrison@hotmail.com
dks3@msn.com
ellie_alexander@hotmail.com
lornawain@btopenworld.com
kakasheh@aol.com
sachai2000@hotmail.com
jenmorsches@aol.com
nickbayat@tidalmedia.co.uk
dlewis@cantor.co.uk
mail@grahamcookson.com
gavski55@hotmail.com
sammiesquire@timeout.com
al_perch@hotmail.com
pearcehouses@hotmail.com
JSMoorcroft@aol.com
HMeyer2650@aol.com
carolinecarberry@hotmail.com
razzlulu@aol.com
gabrielepaniccia@tiscali.co.uk
gnikolica@aol.com
david.webb@hmce.gsi.gov.uk
paulrogroberts@yahoo.co.uk
accurate264@yahoo.com
hannah.delaney@epsom-sthelier.nhs.uk
crazy_gina@hotmail.com
butterflyoji@hotmail.com
tkburgess@duntshill.fsnet.co.uk
russell.hodges@eds.com
sodeskhan@hotmail.com
mariedeguzman72@yahoo.co.uk
chhabrand@aol.com
cyberpaulb@yahoo.com
annafahy@hotmail.com
beckyburrill@yahoo.co.uk
friches@bna.com
kevin@remmingtonvian.co.uk
remond300@yahoo.com
t.pierce@btinternet.com
ismaeldiagne@hotmail.com
michaeljdarbyshire@hotmail.com
torypowell@hotmail.com
dimmock@nildram.co.uk
kieren@grover0203.fsnet.co.uk
marksomebody@yahoo.co.uk
rev.rushton@kingsch.nhs.uk
edward_richards@ml.com
periferalvision@hotmail.com
wilde_won@hotmail.com
mtchlls74@aol.com
michelle.jones@fsa.gov.uk
bergind@hotmail.com
anna@nanoplanet.com
mashdragon@hotmail.com
michael-s-dixon@supanet.com
khallam@banyantreehk.com
namurio@aol.com
pisanchointerior@aol.com
pennyspiller@yahoo.co.uk
anderpln@aol.com
baskacunningham@hotmail.com
clive.deen@oliverjordan.com
rebecca@saltlondon.com
benmein@yahoo.co.uk
dwfharvey@hotmail.com
scottst@ntlworld.com
nkamil@yahoo.com
emma.rutherford@fd.com
amcc311265@aol.com
maryhassell@hotmail.com
srobertson@btconnect.com
accb@richardsbutler.com
komulloy@dfgw.com
nicholas.adlam@ic.ac.uk
j.mackarell@gold.ac.uk
patz@blueyonder.co.uk
ymehrez@hotmail.com
amanda.charles@ons.gov.uk
jennifer.conway@lgim.co.uk
laura_anderson@flextech.co.uk
julie.bishop@ubsw.com
anna.greensmith@bskyb.com
alison@lps.co.uk
alexlburton@hotmail.com
carob@collegeofbodyscience.com
catebw@hotmail.com
ssparkygirl@hotmail.com
c.bird@wellcome.ac.uk
davidchengkl@yahoo.com
eliot@atholestill-sport.co.uk
steve.vosper@homeoffice.gsi.gov.uk
gail.elias@ntlworld.com
fjg@fgood.freeserve.co.uk
sarah_dwyer@hotmail.com
caroline.lumbard@greenergy.co.uk
jamie.dolling@yahoo.co.uk
psaunders90@hotmail.com
mpunton@aol.com
alykhan@hotmail.com
des.stewart@techms.co.uk
nbac56@hotmail.com
rags.martel@granadamedia.com
paulfash@onetel.net.uk
alexander.wharton@rbccm.com
shariefi@ludlowthompson.com
ayshasiddiqua@hotmail.com
clareb1976@hotmail.com
donald@donaldtaylor.co.uk
superssjjay@aol.com
alison.harvey@acnielsen.com.my
dave35brighton@aol.com
emma.knight@drkw.com
BIgoh@lambeth.gov.uk
sharon.singh@mindshareworld.com
paula.L.sheldon@gfuk.com
lkennea@yahoo.co.uk
s.o.thomas@rjw.co.uk
mattfinch100@hotmail.com
dompeyton@hotmail.com
angelawood70@hotmail.com
teresa-smith@ntlworld.com
mariemylordos@hotmail.com
simeon.jones@bbc.co.uk
lucie@422.com
ak_churchgate@hotmail.com
sallie.edwards@rbi.co.uk
ojjo@hotmail.com
georgie.simmonds@citigroup.com
jonathan@forsterinc.co.uk
dlecland@hotmail.com
dlecand1@hotmail.com
sean_phelan@excite.com
Katie.bailiff@centuryfilmsltd.com
martin.whitcombe@cpp.co.uk
tor_taylor@yahoo.com
luke@interagent.co.uk
mazgraphic@aol.com
zakkhan908@hotmail.com
karams@supanet.com
clare.mulheran@hess.com
karams@supnet.com
geez@geezcorp.co.uk
sandradebarros@yahoo.com
layton@btinter.co.uk
angie_laird@hotmail.com
neillgarfield@hotmail.com
jessica.macdermot@centaur.co.uk
lawrencelee@hotmail.com
james.dallow@express.co.uk
sarah.phillis@bskyb.com
bexberlajolli@hotmail.com
georgina.bowman@bbc.co.uk
john@fold7.com
carinabolton@aol.com
williamwalpole@hotmail.com
gswalmsley1@aol.com
klblackburn@hotmail.com
pcallaway@barbican.org.uk
ben@recruitwireless.com
vikster73@hotmail.com
rachel.cook@umusic.com
coates_alan@hotmail.com
andy.flynn@rbi.co.uk
melissawan@hotmail.com
jovid7@mailcity.com
nhathome@btinternet.com
the.gym@virgin.net
ethos@dircon.co.uk
weipin30@hotmail.com
sarajpal@yahoo.co.uk
haoyu_zhang@hotmail.com
david@mandolinstudio.co.uk
jfkdlsl@hfjsk.com
astrogirl72@hotmail.com
gemmabailey@hotmail.com
gomi@btinternet.com
ianrhodes40@hotmail.com
swainson@hotmail.com
meroclcg@yahoo.co.uk
caroline_corcora@hotmail.com
marcusd@mail.com
cheeseboy@hotmail.com
colin.weatherup@db.com
roger@netway.co.uk
miranda@miranda8.freeserve.co.uk
seanarrowsmith@yahoo.co.uk
atacleaning@lineone.net
iboonzaaier@yahoo.co.uk
anne.sheedy@drkw.com
sarah.crow@camden.gov.uk
ryanptollit@hotmail.com
sammy@recoil.org
afh@feller.freeserve.co.uk
rborroff@advanstar.com
mnm@marshall-architecture.co.uk
dhughes@star.net.uk
carolmiers@hotmail.com
patsandtots@hotmail.com
ythomas@dc.com
mark@interagent.co.uk
marion@interagent.co.uk
jon@tuftonland2.co.uk
family@grant-butlers.fsnet.co.uk
ags@britishlibrary.net
barrington@bnbcourtenay.co.uk
naz103@hotmail.com
rkumaresh@hotmail.com
ProductionsOn@aol.com
cymon@totalise.co.uk
babs@io.ocn.ne.jp
christopher71@hotmail.com
ray.monaghan@chp.co.uk
nicolev639@yahoo.com
sfraq@aol.com
depesing@yahoo.com
tarikahmet@hotmail.com
entwistle_john@hotmail.com
barry.rawcliffe@bankofengland.co.uk
mo_wah@yahoo.co.uk
adshea@lycos.co.uk
craigr.robertson@virgin.net
darecki@btinternet.com
suerooney@aol.com
barbaramella@hotmail.com
clare@cpcarter.fsnet.co.uk
kellyandsi@talk21.com
helnelson@hotmail.com
jogregory75@hotmail.com
rkiru@yahoo.com
mark@jory.co.uk
keith.gladdis@news-of-the-world.co.uk
ben.campbell@turner.com
rjidaniel@hotmail.com
karlacma@hotmail.com
sajhanratty@hotmail.com
moule_p96@hotmail.com
davidcampbell007@hotmail.com
richardpullan@hotmail.com
j_sloan_@hotmail.com
joely@runwaydesign.com
lily.y.lau@accenture.com
habibs786@yahoo.co.uk
kuri@lineone.net
ro@easy.com
sarah.allotey@slaughterandmay.com
dd@cartercamerons.co.uk
jac@jcarrigan.freeserve.co.uk
glyn.newberry@virgin.net
kylei@seddons.co.uk
www.joehuss@aol.com
tbrown@hof.co.uk
JustineFisher@aol.com
Nick.glover@ubsw.com
lawrencebotsoff@hotmail.com
pants@pants.com
111@dae.com
fiona.rickards@cibc.co.uk
anamaros@hotmail.com
robin.gilchrist@eu.bovislendlease.com
james.petworth@hotmail.com
kevin.brand@cyrilsweett.com
lorrainemurphy@totalise.co.uk
niallynchuk@yahoo.co.uk
nyasha@friendly-ear.com
rbeacon@channel4.co.uk
kate.blackburn@oxleas.nhs.uk
tomsuji@aol.com
d.kamev@virgin.net
marinho.akinola@dorseylaw.com
judemcook@aol.com
daisylady@talk21879.freeserve.co.uk
marcus_poulton@ml.com
jason.race@talk21.com
jsadourian@hotmail.com
AngelaB1@excite.com
jessefortescue@hotmail.com
tania_cot@hotmail.com
jimwilliams_ely@hotmail.com
daniel@hotmail.com
graham@gseagerplus.com
jameseagle@hotmail.com
zac.abrams@ayh.co.uk
simon_thorne@redcellnetwork.com
ruby.mulraine@bbc.co.uk
daviesjo30@hotmail.com
lawrencechapman@lycos.co.uk
poverton@liberty.co.uk
catherine.hale@btinternet.com
aannelie@yahoo.com
herve.bullot@sainsburys.co.uk
mike@m-cahill.freeserve.co.uk
jeremystannard@yahoo.com
sassyp@zoom.co.uk
rosemary_ds@hotmail.com
angelashetty@yahoo.co.uk
andreahorsfield@hotmail.com
toby@londoncarhire.com
ac24444@aol.com
mjgosnell@hotmail.com
Charles.Quick@camden.gov.uk
mark@markdw.com
mark.d.williams@btinternet.com";

$list_file = "/home/woosterstock/cgi-bin/mailinglist/list.txt";

if (is_writable($list_file)) {
	if (!$handle = fopen($list_file, 'w')) { 
		echo "Could not open list.txt ";
		exit; 
		}	
	if (fwrite($handle, $render) === FALSE) {
		echo "Error writing to list.txt ";
		exit;
		}
	//echo '<p>Mailing List created ('.$emailCount.' clients)</p>';
	fclose($handle);
	}
else {
	echo "list.txt not writable";
	exit;
	}




// ------------- body ---------------
$render_body = $strap.'
'.$addr.'
'.$formatted_price.'

http://www.woosterstock.co.uk/Detail.asp?propID='.$prop_id.'

To arrange a viewing please call our '.$branch.' branch on '.$tel.'

If you do not wish to receive any further emails from us, please reply to this message with the word REMOVE in the subject line.';

echo html_header("Mailing List");
echo '

	<table width="600" align="center">
	  <tr> 
		<td><span class="pageTitle">Mailing List</span></td>
		<td align="right"><a href="property.php?propID='.$prop_id.'">Back to Property</a> &nbsp; &nbsp; <a href="index.php">Main Menu</a></td>
	  </tr>
	</table>
<table width="500" align="center">
<tr>
<td>
<form method="get">
<table border="0">
<tr>
<td>Subject:<br>
	<select name="type" style="width:500px">
	<option value="new">A new property has been added!</option>
	<option value="reduced">A property has been reduced in price</option>
	<option value="back">A property has come back on the market</option>
	</select>
	</td>
</tr>
<tr>
<td>Message:<br>
	<textarea name="message" style="width:500px; height:250px;">'.$render_body.'</textarea></td>
</tr>
<tr>
<td align="center"><input type="submit" value="    Preview and Send    ">
<input type="hidden" name="prop_id" value="'.$prop_id.'">
<input type="hidden" name="count" value="'.$emailCount.'">
<input type="hidden" name="sender" value="'.$sender.'"></td>
<input type="hidden" name="action" value="preview">
</tr>
</table></td>
</tr>
</table>
</body>
</html>
';
}
 
elseif ($_GET["action"] == "preview") {

$prop_id = $_GET["prop_id"];
$type = $_GET["type"];
$count = $_GET["count"];
$sender = $_GET["sender"];
//$subject = $_GET["subject"];
$message = $_GET["message"];
$userid = $_SESSION["s_userid"];

if ($type == "new") { 
	$message = 'Further to your recent enquiry, a new property which may be of interest to you has been added to our website.
	
	'.$message;
	$subject = 'A new property has been added!';
	} elseif ($type == "reduced") { 
	$message = 'Further to your recent enquiry, a property which may be of interest to you has been reduced in price.
	
	'.$message;
	$subject = 'A property has been reduced in price';
	} elseif ($type == "back") { 
	$message = 'Further to your recent enquiry, a property which may be of interest to you has come back on the market.
	
	'.$message;
	$subject = 'A property has come back on the market';
	}


// insert into mailshot table
$sql = "INSERT INTO mailshot 
(mai_type,mai_count,mai_prop,mai_body,mai_sender,mai_userid,mai_date)
VALUES
('$type','$count','$prop_id','$message.','$sender','$userid','$dateToday')";
//$q = $db->query($sql);
//if (DB::isError($q)) {  die("mailshot insert error: ".$q->getMessage()); }
//$id = mysql_insert_id();

$find = "Detail.php?propID=".$prop_id;
$replace = "go.php?id=".$id;
//$message = str_replace($find,$replace,$message);
echo html_header("Mailing List");
echo '
<table width="600" align="center">
	  <tr> 
		<td><span class="pageTitle">Mailing List</span></td>
		<td align="right">&nbsp;</td>
	  </tr>
	</table>
<table width="500" align="center">
<tr>
<td>
<p>&nbsp;</p>
<p>'.$subject.'</p>
<p>'.str_replace("\n","<br>",$message).'</p>
<p><br>The mailing is ready to go. Please click the button below to send this email to '.$count.' customers</p>
<form method="post" action="/cgi-bin/mailinglist/mail-admin.cgi">
<table width="100%">
<tr>
<td align="center">
<input type="hidden" name="subject" value="'.$subject.'">
<input type="hidden" name="message" value="'.$message.'">
<input type="hidden" name="prop_id" value="'.$prop_id.'">
<input type="hidden" name="sender" value="'.$_SESSION["s_user"].'@interagent.co.uk">
<input type="submit" value="    Send Mailshot    ">
</td>
</tr>
</table>
</form>
</td>
</tr>
</table>
</body>
</html>
';

}
?>